# Generated by Django 5.2.9 on 2025-12-15 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datospersonales',
            fields=[
                ('idperfil', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcionperfil', models.CharField(blank=True, max_length=50, null=True)),
                ('perfilactivo', models.BooleanField(default=True)),
                ('apellidos', models.CharField(blank=True, max_length=60, null=True)),
                ('nombres', models.CharField(blank=True, max_length=60, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=20, null=True)),
                ('lugarnacimiento', models.CharField(blank=True, max_length=60, null=True)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('numerocedula', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('estadocivil', models.CharField(blank=True, max_length=50, null=True)),
                ('licenciaconducir', models.CharField(blank=True, max_length=6, null=True)),
                ('telefonoconvencional', models.CharField(blank=True, max_length=15, null=True)),
                ('telefonofijo', models.CharField(blank=True, max_length=15, null=True)),
                ('direcciontrabajo', models.CharField(blank=True, max_length=50, null=True)),
                ('direcciondomiciliaria', models.CharField(blank=True, max_length=50, null=True)),
                ('sitioweb', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'DATOSPERSONALES',
            },
        ),
        migrations.CreateModel(
            name='Cursosrealizados',
            fields=[
                ('idcursorealizado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrecurso', models.CharField(blank=True, max_length=100, null=True)),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('totalhoras', models.IntegerField(blank=True, null=True)),
                ('descripcioncurso', models.CharField(blank=True, max_length=100, null=True)),
                ('entidadpatrocinadora', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60, null=True)),
                ('emailempresapatrocinadora', models.CharField(blank=True, max_length=60, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(blank=True, max_length=100, null=True)),
                ('perfil', models.ForeignKey(blank=True, db_column='idperfilconqueestaactivo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cv.datospersonales')),
            ],
            options={
                'db_table': 'CURSOSREALIZADOS',
            },
        ),
        migrations.CreateModel(
            name='Experiencialaboral',
            fields=[
                ('idexperiencilaboral', models.IntegerField(primary_key=True, serialize=False)),
                ('cargodesempenado', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrempresa', models.CharField(blank=True, max_length=50, null=True)),
                ('lugarempresa', models.CharField(blank=True, max_length=50, null=True)),
                ('emailempresa', models.CharField(blank=True, max_length=100, null=True)),
                ('sitiowebempresa', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrecontactoempresarial', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoempresarial', models.CharField(blank=True, max_length=60, null=True)),
                ('fechainiciogestion', models.DateField(blank=True, null=True)),
                ('fechafingestion', models.DateField(blank=True, null=True)),
                ('descripcionfunciones', models.CharField(blank=True, max_length=100, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(blank=True, max_length=100, null=True)),
                ('perfil', models.ForeignKey(blank=True, db_column='idperfilconqueestaactivo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='cv.datospersonales')),
            ],
            options={
                'db_table': 'EXPERIENCIALABORAL',
            },
        ),
        migrations.CreateModel(
            name='Productosacademicos',
            fields=[
                ('idproductoacademico', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrerecurso', models.CharField(blank=True, max_length=100, null=True)),
                ('clasificador', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(blank=True, db_column='idperfilconqueestaactivo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='cv.datospersonales')),
            ],
            options={
                'db_table': 'PRODUCTOSACADEMICOS',
            },
        ),
        migrations.CreateModel(
            name='Productoslaborales',
            fields=[
                ('idproductoslaborales', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaproducto', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(blank=True, db_column='idperfilconqueestaactivo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_laborales', to='cv.datospersonales')),
            ],
            options={
                'db_table': 'PRODUCTOSLABORALES',
            },
        ),
        migrations.CreateModel(
            name='Reconocimientos',
            fields=[
                ('idreconocimiento', models.IntegerField(primary_key=True, serialize=False)),
                ('tiporeconocimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('fechareconocimiento', models.DateField(blank=True, null=True)),
                ('descripcionreconocimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('entidadpatrocinadora', models.CharField(blank=True, max_length=100, null=True)),
                ('nombrecontactoauspicia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefonocontactoauspicia', models.CharField(blank=True, max_length=60, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.CharField(blank=True, max_length=100, null=True)),
                ('perfil', models.ForeignKey(blank=True, db_column='idperfilconqueestaactivo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='cv.datospersonales')),
            ],
            options={
                'db_table': 'RECONOCIMIENTOS',
            },
        ),
    ]
