# Generated by Django 5.2.9 on 2026-01-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_datospersonales_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='perfilactivo',
            field=models.BooleanField(default=False),
        ),
    ]
