# Generated by Django 5.2.9 on 2026-01-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_datospersonales_perfilactivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permitir_impresion', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'CONFIGURACION_CV',
            },
        ),
    ]
