# Generated by Django 5.2.9 on 2026-01-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_configuracioncv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionCV',
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='permitir_impresion',
            field=models.BooleanField(default=False, help_text='Permite mostrar el botón de imprimir y los certificados'),
        ),
    ]
