# Generated by Django 5.2.9 on 2026-01-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_delete_configuracioncv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursosrealizados',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificados/cursos/'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificados/experiencia/'),
        ),
        migrations.AddField(
            model_name='reconocimientos',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificados/reconocimientos/'),
        ),
    ]
