# Generated by Django 5.2.9 on 2026-01-10 03:52

import cv.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_cursosrealizados_certificado_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificados/cursos/', validators=[cv.models.validar_pdf, django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='permitir_impresion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificados/experiencia/', validators=[cv.models.validar_pdf, django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificados/reconocimientos/', validators=[cv.models.validar_pdf, django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('ideducacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=30)),
                ('institucion', models.CharField(max_length=150)),
                ('titulo_obtenido', models.CharField(blank=True, max_length=150, null=True)),
                ('graduado', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('certificado_pdf', models.FileField(blank=True, null=True, upload_to='certificados/educacion/', validators=[cv.models.validar_pdf, django.core.validators.FileExtensionValidator(['pdf'])])),
                ('perfil', models.ForeignKey(blank=True, db_column='idperfilconqueestaactivo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educaciones', to='cv.datospersonales')),
            ],
            options={
                'db_table': 'EDUCACION',
            },
        ),
    ]
