# Generated by Django 5.2.9 on 2026-01-23 23:23

import cv.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_alter_cursosrealizados_certificado_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='descripcionfunciones',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='fechafingestion',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='fechainiciogestion',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='idexperiencilaboral',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='lugarempresa',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='nombrecontactoempresarial',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='sitiowebempresa',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='telefonocontactoempresarial',
        ),
        migrations.RemoveField(
            model_name='productosacademicos',
            name='nombrerecurso',
        ),
        migrations.RemoveField(
            model_name='productoslaborales',
            name='fechaproducto',
        ),
        migrations.RemoveField(
            model_name='productoslaborales',
            name='idproductoslaborales',
        ),
        migrations.RemoveField(
            model_name='reconocimientos',
            name='descripcionreconocimiento',
        ),
        migrations.RemoveField(
            model_name='reconocimientos',
            name='entidadpatrocinadora',
        ),
        migrations.RemoveField(
            model_name='reconocimientos',
            name='nombrecontactoauspicia',
        ),
        migrations.RemoveField(
            model_name='reconocimientos',
            name='telefonocontactoauspicia',
        ),
        migrations.AddField(
            model_name='cursosrealizados',
            name='certificado_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/imagenes/'),
        ),
        migrations.AddField(
            model_name='cursosrealizados',
            name='certificado_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='certificado_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/imagenes/'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='certificado_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='direccionempresa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='fechafin',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_desde_2000]),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='fechainicio',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_desde_2000]),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='idexperiencialaboral',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='responsabilidades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='telefonoempresa',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='productosacademicos',
            name='certificado_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/imagenes/'),
        ),
        migrations.AddField(
            model_name='productosacademicos',
            name='certificado_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productosacademicos',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificados/', validators=[cv.models.validar_pdf, django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='productosacademicos',
            name='imagenproducto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/academicos/'),
        ),
        migrations.AddField(
            model_name='productosacademicos',
            name='nombreproducto',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='productosacademicos',
            name='rutaimagen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productoslaborales',
            name='certificado_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/imagenes/'),
        ),
        migrations.AddField(
            model_name='productoslaborales',
            name='certificado_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productoslaborales',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificados/', validators=[cv.models.validar_pdf, django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='productoslaborales',
            name='clasificador',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='productoslaborales',
            name='idproductolaboral',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='productoslaborales',
            name='imagenproducto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/laborales/'),
        ),
        migrations.AddField(
            model_name='productoslaborales',
            name='rutaimagen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='reconocimientos',
            name='certificado_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='certificados/imagenes/'),
        ),
        migrations.AddField(
            model_name='reconocimientos',
            name='certificado_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconocimientos',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconocimientos',
            name='entidadotorgante',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificados/', validators=[cv.models.validar_pdf, django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='descripcioncurso',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='emailempresapatrocinadora',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='entidadpatrocinadora',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='fechafin',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_desde_2000]),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='fechainicio',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_desde_2000]),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='idcursorealizado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='nombrecontactoauspicia',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='nombrecurso',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='rutacertificado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='telefonocontactoauspicia',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='descripcionperfil',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciondomiciliaria',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='direcciontrabajo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='idperfil',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='licenciaconducir',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='lugarnacimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='numerocedula',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener exactamente 10 dígitos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sexo',
            field=models.CharField(blank=True, choices=[('H', 'H'), ('M', 'M')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='sitioweb',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonoconvencional',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonofijo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='cargodesempenado',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificados/', validators=[cv.models.validar_pdf, django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='emailempresa',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='nombrempresa',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='rutacertificado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='clasificador',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='idproductoacademico',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='nombreproducto',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificados/', validators=[cv.models.validar_pdf, django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='fechareconocimiento',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_desde_2000]),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='idreconocimiento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='rutacertificado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='tiporeconocimiento',
            field=models.CharField(blank=True, choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Ventagarage',
            fields=[
                ('idventagarage', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(blank=True, max_length=120, null=True)),
                ('estadoproducto', models.CharField(blank=True, choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valordelbien', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('99999.99'))])),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('foto_producto', models.ImageField(blank=True, null=True, upload_to='venta_garage/')),
                ('perfil', models.ForeignKey(blank=True, db_column='idperfilconqueestaactivo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venta_garage', to='cv.datospersonales')),
            ],
            options={
                'db_table': 'VENTAGARAGE',
            },
        ),
        migrations.DeleteModel(
            name='Educacion',
        ),
    ]
