# Generated by Django 5.2.9 on 2026-01-24 17:26

import cv.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_remove_experiencialaboral_descripcionfunciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursosrealizados',
            name='certificado_link',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='certificado_link',
        ),
        migrations.RemoveField(
            model_name='productosacademicos',
            name='certificado_link',
        ),
        migrations.RemoveField(
            model_name='productoslaborales',
            name='certificado_link',
        ),
        migrations.RemoveField(
            model_name='reconocimientos',
            name='certificado_link',
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='fechafin',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_desde_2000, cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='fechainicio',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_desde_2000, cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='estadocivil',
            field=models.CharField(blank=True, choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a'), ('UNION_LIBRE', 'Unión libre')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='licenciaconducir',
            field=models.CharField(blank=True, choices=[('A', 'Tipo A'), ('A1', 'Tipo A1'), ('B', 'Tipo B'), ('C', 'Tipo C'), ('C1', 'Tipo C1'), ('D', 'Tipo D'), ('E', 'Tipo E'), ('F', 'Tipo F'), ('G', 'Tipo G')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechafin',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_desde_2000, cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechainicio',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_desde_2000, cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='fechareconocimiento',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_desde_2000, cv.models.validar_fecha_no_futura]),
        ),
    ]
