# Generated by Django 5.2.9 on 2026-01-24 17:51

import cv.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_remove_cursosrealizados_certificado_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialaboral',
            name='descripcionfunciones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='fechafingestion',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_desde_2000, cv.models.validar_fecha_no_futura]),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='fechainiciogestion',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_desde_2000, cv.models.validar_fecha_no_futura]),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='lugarempresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='nombrecontactoempresarial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='sitiowebempresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='telefonocontactoempresarial',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido.', regex='^[0-9+\\-\\s()]{7,20}$')]),
        ),
        migrations.AddField(
            model_name='productosacademicos',
            name='nombrerecurso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productoslaborales',
            name='fechaproducto',
            field=models.DateField(blank=True, null=True, validators=[cv.models.validar_fecha_desde_2000, cv.models.validar_fecha_no_futura]),
        ),
        migrations.AddField(
            model_name='reconocimientos',
            name='descripcionreconocimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reconocimientos',
            name='entidadpatrocinadora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reconocimientos',
            name='nombrecontactoauspicia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reconocimientos',
            name='telefonocontactoauspicia',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido.', regex='^[0-9+\\-\\s()]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='emailempresapatrocinadora',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='telefonocontactoauspicia',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido.', regex='^[0-9+\\-\\s()]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='totalhoras',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='estadocivil',
            field=models.CharField(blank=True, choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a'), ('UNION_LIBRE', 'Unión libre')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='licenciaconducir',
            field=models.CharField(blank=True, choices=[('A', 'Tipo A'), ('A1', 'Tipo A1'), ('B', 'Tipo B'), ('C', 'Tipo C'), ('C1', 'Tipo C1'), ('D', 'Tipo D'), ('E', 'Tipo E'), ('F', 'Tipo F'), ('G', 'Tipo G')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonoconvencional',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido.', regex='^[0-9+\\-\\s()]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonofijo',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido.', regex='^[0-9+\\-\\s()]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='emailempresa',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='telefonoempresa',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido.', regex='^[0-9+\\-\\s()]{7,20}$')]),
        ),
    ]
