# Generated by Django 5.2.9 on 2026-01-24 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_experiencialaboral_descripcionfunciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='fechafingestion',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='fechainiciogestion',
        ),
        migrations.RemoveField(
            model_name='productoslaborales',
            name='clasificador',
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='telefonocontactoauspicia',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido (solo números y símbolos básicos).', regex='^[0-9+\\-\\s()]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonoconvencional',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido (solo números y símbolos básicos).', regex='^[0-9+\\-\\s()]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='telefonofijo',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido (solo números y símbolos básicos).', regex='^[0-9+\\-\\s()]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='telefonocontactoempresarial',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido (solo números y símbolos básicos).', regex='^[0-9+\\-\\s()]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='telefonoempresa',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido (solo números y símbolos básicos).', regex='^[0-9+\\-\\s()]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='clasificador',
            field=models.CharField(blank=True, choices=[('ARTICULO', 'Artículo'), ('TESIS', 'Tesis'), ('INVESTIGACION', 'Investigación'), ('PROYECTO', 'Proyecto'), ('PONENCIA', 'Ponencia'), ('POSTER', 'Póster'), ('LIBRO', 'Libro / Capítulo'), ('ENSAYO', 'Ensayo'), ('INFORME', 'Informe'), ('OTRO', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='telefonocontactoauspicia',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido (solo números y símbolos básicos).', regex='^[0-9+\\-\\s()]{7,20}$')]),
        ),
    ]
