# Generated by Django 5.2.9 on 2026-01-24 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_remove_experiencialaboral_fechafingestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosrealizados',
            name='perfil',
            field=models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cv.datospersonales'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='perfil',
            field=models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='cv.datospersonales'),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='perfil',
            field=models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, related_name='productos_academicos', to='cv.datospersonales'),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='perfil',
            field=models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, related_name='productos_laborales', to='cv.datospersonales'),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='perfil',
            field=models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, related_name='reconocimientos', to='cv.datospersonales'),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='perfil',
            field=models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, related_name='venta_garage', to='cv.datospersonales'),
        ),
    ]
