# Generated by Django 5.2.9 on 2026-01-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_alter_cursosrealizados_perfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconocimientos',
            name='descripcionreconocimiento',
        ),
    ]
