# Generated by Django 5.2.9 on 2026-01-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_remove_reconocimientos_descripcionreconocimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconocimientos',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='reconocimientos',
            name='entidadotorgante',
        ),
        migrations.AddField(
            model_name='reconocimientos',
            name='descripcionreconocimiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='rutacertificado',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='tiporeconocimiento',
            field=models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=20),
        ),
    ]
