# Generated by Django 5.2.9 on 2026-01-25 20:55

import cv.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_remove_reconocimientos_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, validators=[cv.models.validar_fecha_no_futura]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='fechafin',
            field=models.DateField(validators=[cv.models.validar_fecha_desde_2000, cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='fechainicio',
            field=models.DateField(validators=[cv.models.validar_fecha_desde_2000, cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='nombrecurso',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='apellidos',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='fechanacimiento',
            field=models.DateField(validators=[cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nombres',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='numerocedula',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener exactamente 10 dígitos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='cargodesempenado',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechafin',
            field=models.DateField(validators=[cv.models.validar_fecha_desde_2000, cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fechainicio',
            field=models.DateField(validators=[cv.models.validar_fecha_desde_2000, cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='nombrempresa',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='clasificador',
            field=models.CharField(choices=[('ARTICULO', 'Artículo'), ('TESIS', 'Tesis'), ('INVESTIGACION', 'Investigación'), ('PROYECTO', 'Proyecto'), ('PONENCIA', 'Ponencia'), ('POSTER', 'Póster'), ('LIBRO', 'Libro / Capítulo'), ('ENSAYO', 'Ensayo'), ('INFORME', 'Informe'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productosacademicos',
            name='nombreproducto',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='fechaproducto',
            field=models.DateField(validators=[cv.models.validar_fecha_desde_2000, cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='productoslaborales',
            name='nombreproducto',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='entidadpatrocinadora',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reconocimientos',
            name='fechareconocimiento',
            field=models.DateField(validators=[cv.models.validar_fecha_desde_2000, cv.models.validar_fecha_no_futura]),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='estadoproducto',
            field=models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='nombreproducto',
            field=models.CharField(max_length=120),
        ),
    ]
