# Generated by Django 5.2.9 on 2026-01-25 22:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_ventagarage_fecha_alter_cursosrealizados_fechafin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='sitioweb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='sitiowebempresa',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='valordelbien',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('99999.99'))]),
        ),
        migrations.AddConstraint(
            model_name='cursosrealizados',
            constraint=models.UniqueConstraint(fields=('perfil', 'nombrecurso', 'fechainicio', 'fechafin'), name='uq_curso_perfil_nombre_fechas'),
        ),
        migrations.AddConstraint(
            model_name='experiencialaboral',
            constraint=models.UniqueConstraint(fields=('perfil', 'nombrempresa', 'cargodesempenado', 'fechainicio', 'fechafin'), name='uq_exp_perfil_empresa_cargo_fechas'),
        ),
        migrations.AddConstraint(
            model_name='productosacademicos',
            constraint=models.UniqueConstraint(fields=('perfil', 'nombreproducto', 'clasificador'), name='uq_prodacad_perfil_nombre_clasif'),
        ),
        migrations.AddConstraint(
            model_name='productoslaborales',
            constraint=models.UniqueConstraint(fields=('perfil', 'nombreproducto', 'fechaproducto'), name='uq_prodlab_perfil_nombre_fecha'),
        ),
        migrations.AddConstraint(
            model_name='reconocimientos',
            constraint=models.UniqueConstraint(fields=('perfil', 'tiporeconocimiento', 'fechareconocimiento', 'entidadpatrocinadora'), name='uq_recon_perfil_tipo_fecha_entidad'),
        ),
        migrations.AddConstraint(
            model_name='ventagarage',
            constraint=models.UniqueConstraint(fields=('perfil', 'nombreproducto', 'fecha'), name='uq_venta_perfil_producto_fecha'),
        ),
    ]
