# Generated by Django 5.2.9 on 2026-01-25 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0016_alter_datospersonales_sitioweb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='apellidos',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nombres',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[A-Za-zÁÉÍÓÚÜÑáéíóúüñ\\s]+$')]),
        ),
    ]
