# Generated by Django 5.2.9 on 2026-01-25 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0017_alter_datospersonales_apellidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosacademicos',
            name='nombrerecurso',
        ),
    ]
